# -*- coding: utf-8 -*-
"""permute_variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UvLC0eEQh7rR_lFQV4pF24gyKjVMrluF
    
Keep this python script in the same directory as Model_Permutations.R
"""

def variable_permutations(feature_list):
  listrep = list(feature_list)
  n = len(listrep)
  return [[listrep[k] for k in range(n) if i&1<<k] for i in range(2**n)]
